name: Release
on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 24.x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Set Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
      - name: Extract version
        run: |
          VERSION=$(grep '"version":' package.json | sed -E 's/.*"version": "([^"]+)".*/\1/')
      - name: Delete existing tag if it exists
        run: |
          if git rev-parse "refs/tags/$VERSION" >/dev/null 2>&1; then
            git tag -d $VERSION
            git push --delete origin $VERSION
          fi
      - name: Build
        run: npm run build
      - name: Add dist folder
        run: git add -f dist/
      - name: Create Release Tag
        run: |
          git tag -a $VERSION -m "Release: $VERSION" -f
      - name: Push changes
        run: git push origin main --tags -f