name: Release
on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 24.x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Set Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
      - name: Extract version
        run: |
          echo "VERSION=$(grep '"version":' package.json | sed -E 's/.*"version": "([^"]+)".*/\1/')" >> $GITHUB_ENV
      - name: Delete existing tag if it exists
        run: |
          if git rev-parse "refs/tags/${{ env.VERSION }}" >/dev/null 2>&1; then
            git tag -d ${{ env.VERSION }}
            git push --delete origin ${{ env.VERSION }}
          fi
      - name: Build
        run: npm run build
      - name: Add dist folder
        run: git add -f dist/
      - name: Commit changes
        run: |
          git commit -m "Release ${{ env.VERSION }}" || echo "No changes to commit"
      - name: Create Release Tag
        run: |
          git tag -f ${{ env.VERSION }}
      - name: Push changes
        run: git push -f origin tag ${{ env.VERSION }} -f